FROM ubuntu:bionic

LABEL maintainer="rnp@iastate.edu"

USER root
RUN apt-get update && apt-get install -y software-properties-common \
    && apt-get update && apt-get install -y locales\
    && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8

# add and enable the default user
ARG USER=rnp
RUN adduser --disabled-password --gecos '' $USER
RUN adduser $USER sudo; echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers
