FROM rana2593/prisms-cpfe:sys
MAINTAINER Raghunandan Pratoori "rnp@iastate.edu"

ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get install lsb-release git subversion wget bc libgmp-dev \
    build-essential autoconf automake cmake libtool gfortran python \
    libboost-all-dev zlib1g-dev \
    openmpi-bin openmpi-common libopenmpi-dev \
    libblas3 libblas-dev liblapack3 liblapack-dev libsuitesparse-dev
